name: wishlist
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  build_runner: ^2.4.13
  cloud_firestore: ^5.4.4
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  get_it: ^8.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
